
hosts: ip.of.ec2.instance
  tasks: 
    name: Pull the latest main branch from github
      git: 
        pull 
      notify: build server

  handler:
    tasks: 
      name: If git pull shows a change, build site
        cmd: |
          JEKYLL_ENV=production bundle exec jekyll b

      name: restart docker if needed? 
