--- 

- hosts: all

  tasks: 
    - name: Install tools
      become: true
      apt:
        name:
          - git
          - docker
          - docker-compose
          - ruby-full 
          - build-essential 
          - zlib1g-dev

    - name: Pull the latest main branch from github
      ansible.builtin.git:
        repo: 'https://github.com/oconnordaniel/dans-homepage.git'
        dest: /home/ubuntu/dans-homepage
      notify: build_server

    - community.docker.docker_compose:
        project_name: dans-homepage
        definition:
          version: '2'
          services:
            dans-homepage:
              image: nginx:stable-alpine
              volumes:
                - /home/ubuntu/dans-homepage/_site/:/usr/share/nginx/html/
              ports:
                - "80:80"

  handlers:
    - name: build_server
      ansible.builtin.shell: 
        executable: /bin/bash
        cmd: JEKYLL_ENV=production bundle exec jekyll b
        chdir: /home/ubuntu/dans-homepage

